language: node_js

git:
    # Do not take whole history, but ensure to not break things:
    # - Merging multiple PR's around same time may introduce a case where it's not
    #   the last merge commit that is to be tested
    # - Aside of merge commit we need a previous commit to be able to detect a version switch
    depth: 10

branches:
    only:
        - master # Do not build PR branches
        - /^v\d+\.\d+\.\d+$/ # Ensure to build release tags

stages:
    - name: Test
    - name: Deploy

jobs:
    include:
        # master branch
        - name: "Test - Node.js v12"
          if: branch = master AND type = push
          env:
              - secure: "SkOfCgP58BUhuBu2T4RJHCESl2hNU40NUg7Pa8PW/QgXbnczT0hBGAkoO1pWPkcU672qsCH66ATcmPgeAtAvIouxygh2yNOK1WXsmgpn/3Bdq4XufL/ESjRymPIu/FLbvcvkUGzUwTp1RH2ASiRNWB54RAoiOW6umI04QTrzjk8w/MoFHRvYlf7glJG2f4U3Z9cR/rSRFPMGpGukXl81okTaCbeGkj8f3JyKwcviwpcQhF+u9En2GG95BQyWevdWVaNfqST0fllMdMM5wD+8AlpN3cS0slzREU/9qbOt2v4RpVmQrokhPE+9WYXOB1MlbUKXSl/yzTxPF62Q9bcobO/m6pG+Rtvcc6EvcgYo2XEbPhpZbwx0yqrLInbzviBMr5i42iQ9CPOhTcd71zUmL1EdSNHw1/N5vyc8AYyjzdM2xhLFoe8pg+um8F3KRbpFwX+FTeLVk8DJg6U8ZyuEMXN3cIVF6UqcOnvipZXiRs3knViafEMSlXMjZoNoVXJXDTa79HTes28gjsZRFY6kogESmSV528yDhYUX/SjTxDNFq0d2SyR5R2U5YLTshFi7z+/DXYDK/F+UbOKxL8pe6D1YpHq/vG3eV90UDOxaqU5OpMuMbQO7GOW8DcqLVZ64UspG1PPsGP/JjB3kdZpzPnziJIMXA8TWSyTG8DZTrs4="
          node_js: 12
          script:
              - ls -la .git

        - stage: Deploy
          node_js: 12
          script: skip
          before_deploy:
              - node ./crash.js before_deploy
              - node ./crash.js before_deploy
          after_deploy:
              - node ./crash.js after_deploy
              - node ./crash.js after_deploy
          after_script:
              - node ./crash.js after_script
              - node ./crash.js after_script
          deploy:
              provider: npm
              email: medikoo+npm@medikoo.com
              api_key:
                  secure: mmrt7BUKBTyRmagX8NwEfcRMOCR/uhtJxp07e5L4Eggg/6k+ismOZZ+NFCkQbTLtnp6kGJ8klCF1RWViBmPkdgTmk44UZBmKBaoJgS1YKYcpm1g23Dlx3Wl/heqJStJ7q36H0V4QfkoRxEVnZ/THnZzgIaQUqldpPvC8XFdOuTaDSecXARO7GA9GFd5HZB149Iqx4rSEFHKu6V7gvtYfb7w10TOGTFeauuG3JclCx9H6Q4MiObYO+s2EbwbsOlwnZ1wLp+s3ahjBdzvUp8tLlmcc0hWcKxc3ryC043lffvhEcU0rZz0vbvWzPaeR+AKq0qGy9DweAVd2qIhRblVuNytieyzRer5GBiHlWaIC91li2kxaESzL5xexddzn/38wLrMvV7NuKNbwiaF84BpTkMdiD1kMQbzencDyP0jw4TSVCj4vd+jqVRujCOuNgyMMsUoyTME+Mp9Azl1SQpk3IiAgxtyeuDC4hLFFTwyDp0uqzPNpXOHxObvaIuGk+zxx1mOyI18kms0Z1f+b9EEr72VOUiQaH3uva9PvrcIllrHeG+XK31iPONzV4icpZMIdTl2F27H3oOGMyq+9OxrBZ9rTrH06nc1aGdp/LC50HqwZUQ8Ze4xxOlKHiBzFMwRlJYTC/8XzgopknHftkEMzdTaYGFCQh4e4LetuyajbGHQ=
