title: 🐛 Bug report
description: Create a bug report
body:
  - type: checkboxes
    attributes:
      label: Are you certain there's a bug in a Framework?
      description: If you're uncertain, please report at https://github.com/serverless/serverless/discussions instead
      options:
        - label: Yes it looks as a definite bug
          required: true
  - type: checkboxes
    attributes:
      label: Is the issue in the Framework itself, or maybe it's influenced by external plugin?
      description: If it comes from the plugin, please report at given plugin bug tracker
      options:
        - label: It looks as an issue in Framework itself
          required: true
  - type: checkboxes
    attributes:
      label: Are you using latest version of the Framework
      description: Latest version can be checked at https://github.com/serverless/serverless/releases/latest
      options:
        - label: Yes, I'm using latest version
          required: true
