name: ci/cd

on:
  push:
    branches: [master]
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  tagNewVersion:
    name: Tag new version
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    env:
      GET_LAST_VALIDATED_COMMIT_HASH_URL: ${{ secrets.GET_LAST_VALIDATED_COMMIT_HASH_URL }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PUT_LAST_VALIDATED_COMMIT_HASH_URL: ${{ secrets.PUT_LAST_VALIDATED_COMMIT_HASH_URL }}
    steps:
      # Checkout repository
      - uses: actions/checkout@v2
        with:
          fetch-depth: 30

      # Resolve last validated commit hash (and store current as last validated)
      # Note: Last validated hash is needed resolve pushed commits range
      - run: |
          curl -f "$GET_LAST_VALIDATED_COMMIT_HASH_URL" -o /home/runner/last-validated-commit-hash || :
          curl -v -X PUT -H "User-Agent:" -H "Accept:" -H "Content-Type:" -d "$GITHUB_SHA" "$PUT_LAST_VALIDATED_COMMIT_HASH_URL"

      # Ensure to cache ~/.npm and node_modules
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-${{ github.ref }}-${{ hashFiles('package.json') }}
          restore-keys: npm-${{ runner.os }}-${{ github.ref }}-
      - uses: actions/cache@v1
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-${{ github.ref }}-${{ hashFiles('package.json') }}
          restore-keys: node-modules-${{ runner.os }}-${{ github.ref }}-

      # If "version" in package.json was bumped in pushed commits range tag new version
      - run: |
          LAST_VALIDATED_COMMIT_HASH=`cat /home/runner/last-validated-commit-hash` || :
          if [ -n "$LAST_VALIDATED_COMMIT_HASH" ];
          then
            NEW_VERSION=`git diff $LAST_VALIDATED_COMMIT_HASH package.json | grep '"version": "' | tail -n 1 | grep -oE "[0-9]+\.[0-9]+\.[0-9]+"` || :
            if [ -n "$NEW_VERSION" ];
            then
              git tag v$NEW_VERSION
              git push https://$GITHUB_TOKEN@github.com/medikoo/package-local-test --tags
            fi
          fi

      # Setup Node.js
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: https://registry.npmjs.org

      # Install dependencies
      - run: |
          echo "FOO"
          npm update --no-save
          echo "BAR"
          npm update --save-dev --no-save
          cat ~/.npmrc
  # publishNewVersion:
  #   name: Publish new version
  #   if: startsWith(github.ref, 'refs/tags/v')
  #   runs-on: ubuntu-latest
  #   env:
  #     NPM_API_KEY: ${{ secrets.NPM_API_KEY }}
