name: ci/cd

on:
  push:
    branches: [master]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: last-validated-commit-hash
      - run: cat last-validated-commit-hash
      - run: echo $GITHUB_SHA > last-validated-commit-hash
      - uses: actions/upload-artifact@v2
        with:
          name: last-validated-commit-hash
          path: last-validated-commit-hash
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - run: npm install
      - run: npm run lint
