name: ci/cd

on:
  push:
    branches: [master]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      GET_LAST_VALIDATED_COMMIT_HASH_URL: ${{ secrets.GET_LAST_VALIDATED_COMMIT_URL }}
    steps:
      - uses: actions/checkout@v2
      - run: pwd
      - run: curl "$GET_LAST_VALIDATED_COMMIT_HASH_URL" -o last-validated-commit-hash
      - run: cat last-validated-commit-hash
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - run: npm install
      - run: npm run lint
