# PR's only
name: Validate proposal

on:
  pull_request:
    branches: [master]

jobs:
  validateProposal:
    name: Validate proposal
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Ensure to have working git diff against master
      - name: Retrieve last master commit (for `git diff` purposes)
        run: |
          git checkout -b pr
          git fetch --prune --depth=1 origin +refs/heads/master:refs/remotes/origin/master
          git checkout master
          git checkout pr

      # Ensure to cache ~/.npm and node_modules
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-${{ github.ref }}-${{ hashFiles('package.json') }}
          restore-keys: |
            npm-${{ runner.os }}-${{ github.ref }}-
            npm-${{ runner.os }}-refs/heads/master-
      - uses: actions/cache@v1
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-${{ github.ref }}-${{ hashFiles('package.json') }}
          restore-keys: |
            node-modules-${{ runner.os }}-${{ github.ref }}-
            node-modules-${{ runner.os }}-refs/heads/master-

      # Setup Node.js & npm
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - if: steps.cache.outputs.cache-hit != 'true'
        run: npm update --no-save
      - if: steps.cache.outputs.cache-hit != 'true'
        run: npm update --save-dev --no-save
      - run: npm run prettier-check:updated
      - run: npm run lint:updated
      - run: git status
      - run: cat package.json
